server:
  port: 4004

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth-service-route
          uri: http://localhost:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: inmate-service-route
          uri: http://localhost:4007
          predicates:
            - Path=/api/inmates/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: rehabilitation-service-route
          uri: http://localhost:4006
          predicates:
            - Path=/api/rehabilitation/**
          filters:
            - StripPrefix=1
            - JwtValidation
        
        - id: api-docs-auth-route
          uri: http://localhost:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs
        
        - id: api-docs-inmate-route
          uri: http://localhost:4007
          predicates:
            - Path=/api-docs/inmates
          filters:
            - RewritePath=/api-docs/inmates,/v3/api-docs

        - id: api-docs-rehabilitation-route
          uri: http://localhost:4006
          predicates:
            - Path=/api-docs/rehabilitation
          filters:
            - RewritePath=/api-docs/rehabilitation,/v3/api-docs

auth:
  service:
    url: http://localhost:4005

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
